# Generated by Django 5.2.5 on 2025-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=32, unique=True)),
                ('expire', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('expired', 'expired'), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
