# Generated by Django 5.2.5 on 2025-09-01 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(default='', editable=False, max_length=40, unique=True)),
                ('sender_card_number', models.CharField(max_length=20)),
                ('receiver_card_number', models.CharField(max_length=20)),
                ('sender_card_expiry', models.CharField(max_length=5)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('sending_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('643', 'RUB'), ('840', 'USD'), ('860', 'UZS')])),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('state', models.IntegerField(choices=[(1, 'created'), (2, 'confirmed'), (3, 'cancelled')], default=1)),
                ('try_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('otp', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
